ask_gemini <- function(prompt, api_key = Sys.getenv("GEMINI_API_KEY"), 
                       format_output = TRUE, save_to_file = FALSE, 
                       filename = NULL) {
  
  # Load required libraries
  library(httr)
  library(jsonlite)
  library(stringr)
  
  # Construct API URL
  url <- paste0("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=", api_key)
  
  # Prepare request body
  body <- list(
    contents = list(
      list(parts = list(list(text = prompt)))
    )
  )
  
  # Make API request with timeout and retry logic
  max_retries <- 3
  timeout_seconds <- 60
  
  for (attempt in 1:max_retries) {
    tryCatch({
      res <- POST(
        url,
        body = toJSON(body, auto_unbox = TRUE),
        content_type_json(),
        timeout(timeout_seconds)
      )
      break  # Success, exit retry loop
    }, error = function(e) {
      if (attempt == max_retries) {
        stop("API request failed after ", max_retries, " attempts. Error: ", e$message)
      }
      cat("Attempt", attempt, "failed. Retrying in 2 seconds...\n")
      Sys.sleep(2)
    })
  }
  
  # Parse response
  parsed <- content(res, as = "parsed")
  
  # Handle API errors
  if (!is.null(parsed$error)) {
    stop("Gemini API Error: ", parsed$error$message)
  }
  
  # Extract raw text
  raw_text <- parsed$candidates[[1]]$content$parts[[1]]$text
  
  if (format_output) {
    # Enhanced cleaning for better formatting
    cleaned_text <- raw_text |>
      # Remove code block markers
      str_remove_all("^```[a-zA-Z]*\\s*|```$") |>
      # Replace escaped newlines with actual newlines
      str_replace_all("\\\\n", "\n") |>
      # Replace escaped quotes
      str_replace_all('\\"', '"') |>
      # Replace escaped tabs
      str_replace_all("\\\\t", "\t") |>
      # Clean up multiple consecutive newlines
      str_replace_all("\n{3,}", "\n\n") |>
      # Remove leading/trailing whitespace
      str_trim()
    
    # Format and display the output nicely
    cat("\n" %+% paste(rep("=", 80), collapse = "") %+% "\n")
    cat("GEMINI RESPONSE\n")
    cat(paste(rep("=", 80), collapse = "") %+% "\n\n")
    cat(cleaned_text)
    cat("\n\n" %+% paste(rep("=", 80), collapse = "") %+% "\n")
    
    # Optional: Save to file
    if (save_to_file) {
      if (is.null(filename)) {
        filename <- paste0("gemini_response_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".Rmd")
      }
      
      # Create R Markdown formatted content
      rmd_content <- paste0(
        "---\n",
        "title: \"Gemini AI Response\"\n",
        "author: \"Generated by Gemini\"\n",
        "date: \"", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\"\n",
        "output: html_document\n",
        "---\n\n",
        "## Prompt\n\n",
        substr(prompt, 1, 200), ifelse(nchar(prompt) > 200, "...", ""), "\n\n",
        "## Response\n\n",
        "```{r}\n",
        cleaned_text, "\n",
        "```"
      )
      
      writeLines(rmd_content, filename)
      cat("Response saved to:", filename, "\n")
    }
    
    # Return cleaned text invisibly so it doesn't print again
    invisible(cleaned_text)
    
  } else {
    # Return raw text without formatting
    return(raw_text)
  }
}

# Helper function for string concatenation (if %+% doesn't exist)
`%+%` <- function(a, b) paste0(a, b)

# Enhanced version with additional options
ask_gemini_advanced <- function(prompt, api_key = Sys.getenv("GEMINI_API_KEY"),
                                display_formatted = TRUE, 
                                return_cleaned = TRUE,
                                save_to_file = FALSE,
                                filename = NULL,
                                open_file = FALSE) {
  
  library(httr)
  library(jsonlite)
  library(stringr)
  
  url <- paste0("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=", api_key)
  
  body <- list(
    contents = list(
      list(parts = list(list(text = prompt)))
    )
  )
  
  # Make API request with enhanced error handling
  max_retries <- 3
  timeout_seconds <- 60
  
  for (attempt in 1:max_retries) {
    tryCatch({
      res <- POST(
        url,
        body = toJSON(body, auto_unbox = TRUE),
        content_type_json(),
        timeout(timeout_seconds)
      )
      break  # Success, exit retry loop
    }, error = function(e) {
      if (attempt == max_retries) {
        stop("API request failed after ", max_retries, " attempts. Error: ", e$message)
      }
      cat("Attempt", attempt, "failed. Retrying in 2 seconds...\n")
      Sys.sleep(2)
    })
  }
  
  parsed <- content(res, as = "parsed")
  
  if (!is.null(parsed$error)) {
    stop("Gemini API Error: ", parsed$error$message)
  }
  
  raw_text <- parsed$candidates[[1]]$content$parts[[1]]$text
  
  # Enhanced text cleaning
  cleaned_text <- raw_text |>
    str_remove_all("^```[a-zA-Z]*\\s*|```$") |>
    str_replace_all("\\\\n", "\n") |>
    str_replace_all('\\"', '"') |>
    str_replace_all("\\\\t", "\t") |>
    str_replace_all("\n{3,}", "\n\n") |>
    str_trim()
  
  if (display_formatted) {
    # Create a nice header
    header <- paste(rep("=", 80), collapse = "")
    cat("\n", header, "\n")
    cat("🤖 GEMINI RESPONSE\n")
    cat(header, "\n\n")
    
    # Display the cleaned text
    cat(cleaned_text)
    
    # Create footer
    cat("\n\n", header, "\n")
    cat("✅ Response generated at:", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n")
    cat(header, "\n")
  }
  
  # Save to file if requested
  if (save_to_file) {
    if (is.null(filename)) {
      filename <- paste0("gemini_response_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".Rmd")
    }
    
    # Create R Markdown formatted content
    rmd_content <- paste0(
      "---\n",
      "title: \"Gemini AI Response\"\n",
      "author: \"Generated by Gemini\"\n",
      "date: \"", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\"\n",
      "output: html_document\n",
      "---\n\n",
      "## Prompt\n\n",
      substr(prompt, 1, 200), ifelse(nchar(prompt) > 200, "...", ""), "\n\n",
      "## Response\n\n",
      "```{r}\n",
      cleaned_text, "\n",
      "```"
    )
    
    writeLines(rmd_content, filename)
    cat("💾 Response saved to:", filename, "\n")
    
    # Optionally open the file
    if (open_file && interactive()) {
      file.edit(filename)
    }
  }
  
  # Return based on preference
  if (return_cleaned) {
    invisible(cleaned_text)
  } else {
    invisible(raw_text)
  }
}

# Example usage functions
demo_gemini <- function() {
  cat("Demo: Basic usage\n")
  ask_gemini("Write a simple R function to calculate mean and standard deviation")
  
  cat("\n\nDemo: Advanced usage with file saving\n")
  ask_gemini_advanced(
    "Create an R function for data visualization", 
    save_to_file = TRUE,
    filename = "gemini_viz_function.R"
  )
}